# 전처리 연습 (Tokenize, Cleansing & Normalization, Stemming & Lemmatization)

1. 데이터셋을 찾는다. (만들어진, 크롤링, ...)
2. 전처리

In [66]:
import pandas as pd

data = pd.read_table('./steam.txt')
data['document'].head()

0                               노래가 너무 적음
1         돌겠네 진짜. 황숙아, 어크 공장 그만 돌려라. 죽는다.
2        막노동 체험판 막노동 하는사람인데 장비를 내가 사야돼 뭐지
3    차악!차악!!차악!!! 정말 이래서 왕국을 되찾을 수 있는거야??
4     시간 때우기에 좋음.. 도전과제는 50시간이면 다 깰 수 있어요
Name: document, dtype: str

In [67]:
import re

# 한글만 남김
pattern1 = re.compile(r'[^가-힣\s]')
# 여러 개의 공백을 하나로 매핑
pattern2 = re.compile(r'\s+')

clean_list = []

for text in data['document']:
    text = pattern1.sub(' ', text)
    text = pattern2.sub(' ', text)
    clean_list.append(text)

data['document'] = clean_list
data.head()

   label                          document
0      0                         노래가 너무 적음
1      0      돌겠네 진짜 황숙아 어크 공장 그만 돌려라 죽는다
2      1  막노동 체험판 막노동 하는사람인데 장비를 내가 사야돼 뭐지
3      1   차악 차악 차악 정말 이래서 왕국을 되찾을 수 있는거야
4      1   시간 때우기에 좋음 도전과제는 시간이면 다 깰 수 있어요

In [68]:
pattern = re.compile(r'(\b\w+\b)( \1)+')

normal_list = []

for text in data['document']:
    text = pattern.sub(r'\1\1', text)
    normal_list.append(text)

data['document'] = normal_list
data.head(20)

    label                                           document
0       0                                          노래가 너무 적음
1       0                       돌겠네 진짜 황숙아 어크 공장 그만 돌려라 죽는다
2       1                   막노동 체험판 막노동 하는사람인데 장비를 내가 사야돼 뭐지
3       1                        차악차악 정말 이래서 왕국을 되찾을 수 있는거야
4       1                    시간 때우기에 좋음 도전과제는 시간이면 다 깰 수 있어요
5       1               역시 재미있네요 전작에서 할수 없었던 자유로운 덱 빌딩도 좋네요
6       1                                           재미있었습니다
7       1                                   은근 쉽지만 은근 어려운 게임
8       0  베 스다 이 개 끼들아 시작할 때 체스판 돌아가는거 분동안 번 봤더나 빡치네 진짜 ...
9       1                                  시간 분동안 스트레스 다 풀림
10      0                                  걍 겜임 계정을 못만들어 미친겜
11      0                                         관람객 호랑이 불가
12      1                             재미쩡 초반에 좀 힘들어여 도트라서 조아
13      1  포켓볼 도 몰랐는데 이걸로 배워 갑니다 심심할때 하면 좋아요 컴퓨터 상대하는거 제대...
14      1                                      트레이아크 사랑해요 핰핰
15      0                 좆망겜 하지마 무슨 처음에 키자마자 매칭이 왜 렙하고 매칭되냐
16      1  뭐랄까 다크소울하는느낌이에요 죽으면 돈 다날라가는 방식 렙업하면서 무한 반복인거같은...
17      1  원하는거 보실려면 홈페이지 가셔서 패치를 사셔야 합니다 패치가 만원이라 사실상 만원...
18      0  안해 썩을 까진 그냥 대충 슥슥해도 되더니 에서 판때기를 직접 사용하는데 판을 밟는...
19      0                                                 우웩

In [69]:
from konlpy.tag import Okt

okt = Okt()

token_list = []

for text in data['document']:
    tokens = okt.morphs(text, stem=True)
    token_list.append(tokens)
    

data['tokens'] = token_list
data.head(20)

,label,document,tokens
0,0,노래가 너무 적음,"[노래, 가, 너무, 적다]"
1,0,돌겠네 진짜 황숙아 어크 공장 그만 돌려라 죽는다,"[돌다, 진짜, 황숙, 아, 어크, 공장, 그만, 돌리다, 죽다]"
2,1,막노동 체험판 막노동 하는사람인데 장비를 내가 사야돼 뭐지,"[막노동, 체험판, 막노동, 하다, 사람, 인데, 장비, 를, 내, 가, 사다, 돼..."
3,1,차악차악 정말 이래서 왕국을 되찾을 수 있는거야,"[차악차악, 정말, 이래서, 왕국, 을, 되찾다, 수, 있다]"
4,1,시간 때우기에 좋음 도전과제는 시간이면 다 깰 수 있어요,"[시간, 때우다, 좋다, 도전, 과제, 는, 시간, 이면, 다, 깨다, 수, 있다]"
5,1,역시 재미있네요 전작에서 할수 없었던 자유로운 덱 빌딩도 좋네요,"[역시, 재미있다, 전작, 에서, 하다, 없다, 자유롭다, 덱, 빌딩, 도, 좋다]"
6,1,재미있었습니다,[재미있다]
7,1,은근 쉽지만 은근 어려운 게임,"[은근, 쉬다, 은근, 어렵다, 게임]"
8,0,베 스다 이 개 끼들아 시작할 때 체스판 돌아가는거 분동안 번 봤더나 빡치네 진짜 ...,"[베, 스, 다, 이, 개, 끼, 들, 아, 시작, 하다, 때, 체스판, 돌아가다,..."
9,1,시간 분동안 스트레스 다 풀림,"[시간, 분동, 안, 스트레스, 다, 풀림]"
10,0,걍 겜임 계정을 못만들어 미친겜,"[걍, 겜임, 계정, 을, 못, 만들다, 미치다, 겜]"
11,0,관람객 호랑이 불가,"[관람객, 호랑이, 불가]"
12,1,재미쩡 초반에 좀 힘들어여 도트라서 조아,"[재미, 쩡, 초반, 에, 좀, 힘들다, 도트, 라서, 조아]"
13,1,포켓볼 도 몰랐는데 이걸로 배워 갑니다 심심할때 하면 좋아요 컴퓨터 상대하는거 제대...,"[포켓볼, 도, 모르다, 이, 걸, 로, 배우다, 가다, 심심하다, 때, 하다, 좋..."
14,1,트레이아크 사랑해요 핰핰,"[트레이아크, 사랑, 하다, 핰핰]"
15,0,좆망겜 하지마 무슨 처음에 키자마자 매칭이 왜 렙하고 매칭되냐,"[좆망, 겜, 하다, 무슨, 처음, 에, 키, 자마자, 매칭, 이, 왜, 렙, 하고..."
16,1,뭐랄까 다크소울하는느낌이에요 죽으면 돈 다날라가는 방식 렙업하면서 무한 반복인거같은...,"[뭐라다, 다크, 소울, 하, 는, 느낌, 이에요, 죽다, 돈, 다날, 라가, 는,..."
17,1,원하는거 보실려면 홈페이지 가셔서 패치를 사셔야 합니다 패치가 만원이라 사실상 만원...,"[원하다, 보다, 홈페이지, 갈다, 패치, 를, 사다, 하다, 패치, 가, 만원, ..."
18,0,안해 썩을 까진 그냥 대충 슥슥해도 되더니 에서 판때기를 직접 사용하는데 판을 밟는...,"[안해, 썩을, 까진, 그냥, 대충, 슥, 슥, 해도, 되다, 에서, 판때, 기르다..."
19,0,우웩,[우웩]

In [70]:
ko_stopwords = set("아 휴 아이구 아이쿠 아이고 어 나 우리 저희 따라 의해 을 를 에 의 가 으로 로 에게 뿐이다 의거하여 근거하여 입각하여 기준으로 예하면 예를 들면 예를 들자면 저 소인 소생 저희 지말고 하지마 하지마라 다른 물론 또한 그리고 비길수 없다 해서는 안된다 뿐만 아니라 만이 아니다 만은 아니다 막론하고 관계없이 그치지 않다 그러나 그런데 하지만 든간에 논하지 않다 따지지 않다 설사 비록 더라도 아니면 만 못하다 하는 편이 낫다 불문하고 향하여 향해서 향하다 쪽으로 틈타 이용하여 타다 오르다 제외하고 이 외에 이 밖에 하여야 비로소 한다면 몰라도 외에도 이곳 여기 부터 기점으로 따라서 할 생각이다 하려고하다 이리하여 그리하여 그렇게 함으로써 하지만 일때 할때 앞에서 중에서 보는데서 으로써 로써 까지 해야한다 일것이다 반드시 할줄알다 할수있다 할수있어 임에 틀림없다 한다면 등 등등 제 겨우 단지 다만 할뿐 딩동 댕그 대해서 대하여 대하면 훨씬 얼마나 얼마만큼 얼마큼 남짓 여 얼마간 약간 다소 좀 조금 다수 몇 얼마 지만 하물며 또한 그러나 그렇지만 하지만 이외에도 대해 말하자면 뿐이다 다음에 반대로 반대로 말하자면 이와 반대로 바꾸어서 말하면 바꾸어서 한다면 만약 그렇지않으면 까악 툭 딱 삐걱거리다 보드득 비걱거리다 꽈당 응당 해야한다 에 가서 각 각각 여러분 각종 각자 제각기 하도록하다 와 과 그러므로 그래서 고로 한 까닭에 하기 때문에 거니와 이지만 대하여 관하여 관한 과연 실로 아니나다를가 생각한대로 진짜로 한적이있다 하곤하였다 하 하하 허허 아하 거바 와 오 왜 어째서 무엇때문에 어찌 하겠는가 무슨 어디 어느곳 더군다나 하물며 더욱이는 어느때 언제 야 이봐 어이 여보시오 흐흐 흥 휴 헉헉 헐떡헐떡 영차 여차 어기여차 끙끙 아야 앗 아야 콸콸 졸졸 좍좍 뚝뚝 주룩주룩 솨 우르르 그래도 또 그리고 바꾸어말하면 바꾸어말하자면 혹은 혹시 답다 및 그에 따르는 때가 되어 즉 지든지 설령 가령 하더라도 할지라도 일지라도 지든지 몇 거의 하마터면 인젠 이젠 된바에야 된이상 만큼	어찌됏든 그위에 게다가 점에서 보아 비추어 보아 고려하면 하게될것이다 일것이다 비교적 좀 보다더 비하면 시키다 하게하다 할만하다 의해서 연이서 이어서 잇따라 뒤따라 뒤이어 결국 의지하여 기대여 통하여 자마자 더욱더 불구하고 얼마든지 마음대로 주저하지 않고 곧 즉시 바로 당장 하자마자 밖에 안된다 하면된다 그래 그렇지 요컨대 다시 말하자면 바꿔 말하면 즉 구체적으로 말하자면 시작하여 시초에 이상 허 헉 허걱 바와같이 해도좋다 해도된다 게다가 더구나 하물며 와르르 팍 퍽 펄렁 동안 이래 하고있었다 이었다 에서 로부터 까지 예하면 했어요 해요 함께 같이 더불어 마저 마저도 양자 모두 습니다 가까스로 하려고하다 즈음하여 다른 다른 방면으로 해봐요 습니까 했어요 말할것도 없고 무릎쓰고 개의치않고 하는것만 못하다 하는것이 낫다 매 매번 들 모 어느것 어느 로써 갖고말하자면 어디 어느쪽 어느것 어느해 어느 년도 라 해도 언젠가 어떤것 어느것 저기 저쪽 저것 그때 그럼 그러면 요만한걸 그래 그때 저것만큼 그저 이르기까지 할 줄 안다 할 힘이 있다 너 너희 당신 어찌 설마 차라리 할지언정 할지라도 할망정 할지언정 구토하다 게우다 토하다 메쓰겁다 옆사람 퉤 쳇 의거하여 근거하여 의해 따라 힘입어 그 다음 버금 두번째로 기타 첫번째로 나머지는 그중에서 견지에서 형식으로 쓰여 입장에서 위해서 단지 의해되다 하도록시키다 뿐만아니라 반대로 전후 전자 앞의것 잠시 잠깐 하면서 그렇지만 다음에 그러한즉 그런즉 남들 아무거나 어찌하든지 같다 비슷하다 예컨대 이럴정도로 어떻게 만약 만일 위에서 서술한바와같이 인 듯하다 하지 않는다면 만약에 무엇 무슨 어느 어떤 아래윗 조차 한데 그럼에도 불구하고 여전히 심지어 까지도 조차도 하지 않도록 않기 위하여 때 시각 무렵 시간 동안 어때 어떠한 하여금 네 예 우선 누구 누가 알겠는가 아무도 줄은모른다 줄은 몰랏다 하는 김에 겸사겸사 하는바 그런 까닭에 한 이유는 그러니 그러니까 때문에 그 너희 그들 너희들 타인 것 것들 너 위하여 공동으로 동시에 하기 위하여 어찌하여 무엇때문에 붕붕 윙윙 나 우리 엉엉 휘익 윙윙 오호 아하 어쨋든 만 못하다	하기보다는 차라리 하는 편이 낫다 흐흐 놀라다 상대적으로 말하자면 마치 아니라면 쉿 그렇지 않으면 그렇지 않다면 안 그러면 아니었다면 하든지 아니면 이라면 좋아 알았어 하는것도 그만이다 어쩔수 없다 하나 일 일반적으로 일단 한켠으로는 오자마자 이렇게되면 이와같다면 전부 한마디 한항목 근거로 하기에 아울러 하지 않도록 않기 위해서 이르기까지 이 되다 로 인하여 까닭으로 이유만으로 이로 인하여 그래서 이 때문에 그러므로 그런 까닭에 알 수 있다 결론을 낼 수 있다 으로 인하여 있다 어떤것 관계가 있다 관련이 있다 연관되다 어떤것들 에 대해 이리하여 그리하여 여부 하기보다는 하느니 하면 할수록 운운 이러이러하다 하구나 하도다 다시말하면 다음으로 에 있다 에 달려 있다 우리 우리들 오히려 하기는한데 어떻게 어떻해 어찌됏어 어때 어째서 본대로 자 이 이쪽 여기 이것 이번 이렇게말하자면 이런 이러한 이와 같은 요만큼 요만한 것 얼마 안 되는 것 이만큼 이 정도의 이렇게 많은 것 이와 같다 이때 이렇구나 것과 같이 끼익 삐걱 따위 와 같은 사람들 부류의 사람들 왜냐하면 중의하나 오직 오로지 에 한하다 하기만 하면 도착하다 까지 미치다 도달하다 정도에 이르다 할 지경이다 결과에 이르다 관해서는 여러분 하고 있다 한 후 혼자 자기 자기집 자신 우에 종합한것과같이 총적으로 보면 총적으로 말하면 총적으로 대로 하다 으로서 참 그만이다 할 따름이다 쿵 탕탕 쾅쾅 둥둥 봐 봐라 아이야 아니 와아 응 아이 참나 년 월 일 령 영 일 이 삼 사 오 육 륙 칠 팔 구 이천육 이천칠 이천팔 이천구 하나 둘 셋 넷 다섯 여섯 일곱 여덟 아홉 령 영 ".split())

In [76]:
token_list

[['노래', '가', '너무', '적다'],
 ['돌다', '진짜', '황숙', '아', '어크', '공장', '그만', '돌리다', '죽다'],
 ['막노동',
  '체험판',
  '막노동',
  '하다',
  '사람',
  '인데',
  '장비',
  '를',
  '내',
  '가',
  '사다',
  '돼다',
  '뭐',
  '지'],
 ['차악차악', '정말', '이래서', '왕국', '을', '되찾다', '수', '있다'],
 ['시간', '때우다', '좋다', '도전', '과제', '는', '시간', '이면', '다', '깨다', '수', '있다'],
 ['역시', '재미있다', '전작', '에서', '하다', '없다', '자유롭다', '덱', '빌딩', '도', '좋다'],
 ['재미있다'],
 ['은근', '쉬다', '은근', '어렵다', '게임'],
 ['베',
  '스',
  '다',
  '이',
  '개',
  '끼',
  '들',
  '아',
  '시작',
  '하다',
  '때',
  '체스판',
  '돌아가다',
  '분동',
  '안',
  '번',
  '보다',
  '더',
  '나',
  '빡치다',
  '진짜',
  '무한',
  '로딩',
  '버그',
  '안',
  '치다',
  '고치다',
  '겜',
  '하다',
  '거',
  '냐'],
 ['시간', '분동', '안', '스트레스', '다', '풀림'],
 ['걍', '겜임', '계정', '을', '못', '만들다', '미치다', '겜'],
 ['관람객', '호랑이', '불가'],
 ['재미', '쩡', '초반', '에', '좀', '힘들다', '도트', '라서', '조아'],
 ['포켓볼',
  '도',
  '모르다',
  '이',
  '걸',
  '로',
  '배우다',
  '가다',
  '심심하다',
  '때',
  '하다',
  '좋다',
  '컴퓨터',
  '상대',
  '하다',
  '제대로',
  '이기다',
  '보고',
  '싶다',
  '자다',
  '안되다'],
 ['트레이아크', '사랑', '하다', '핰핰'],
 ['좆망',
  '겜',
  '하다',
  '무슨',
  '처음',
  '에',
  '키',
  '자마자',
  '매칭',
  '이',
  '왜',
  '렙',
  '하고',
  '매칭',
  '되다'],
 ['뭐라다',
  '다크',
  '소울',
  '하',
  '는',
  '느낌',
  '이에요',
  '죽다',
  '돈',
  '다날',
  '라가',
  '는',
  '방식',
  '렙업',
  '하다',
  '무한',
  '반복',
  '인거',
  '같다',
  '재미있다',
  '클래스',
  '도',
  '은근',
  '많다',
  '같다',
  '또',
  '캐릭터',
  '를',
  '계속',
  '추가',
  '하다',
  '예정',
  '인가',
  '같다',
  '그리고',
  '하다',
  '요소',
  '하고',
  '매번',
  '던전',
  '도',
  '바뀌다',
  '재미있다',
  '돈',
  '이',
  '아깝다',
  '않다',
  '생각',
  '드',
  '네',
  '요'],
 ['원하다',
  '보다',
  '홈페이지',
  '갈다',
  '패치',
  '를',
  '사다',
  '하다',
  '패치',
  '가',
  '만원',
  '이라',
  '사실',
  '상',
  '만원',
  '주다',
  '게임',
  '을',
  '살다',
  '건데',
  '좋다'],
 ['안해',
  '썩을',
  '까진',
  '그냥',
  '대충',
  '슥',
  '슥',
  '해도',
  '되다',
  '에서',
  '판때',
  '기르다',
  '직접',
  '사용',
  '하다',
  '판',
  '을',
  '밟다',
  '순간',
  '서다',
  '땅',
  '이',
  '변하다',
  '버리다',
  '뭔가',
  '억울하다',
  '하다',
  '싫어지다',
  '그래도',
  '일단',
  '이',
  '놈',
  '을',
  '못자다',
  '왠지',
  '못',
  '깨다',
  '안',
  '하다',
  '같다',
  '깨다',
  '접다'],
 ['우웩'],
 ['로지텍', '마우스', '가', '드디어', '일', '한', '게임', '매크로', '없다', '흑우', '없다', '제'],
 ['디스플레이', '에', '다소', '버그', '가', '있다', '게임', '자체', '는', '훌륭하다'],
 ['압도',
  '적',
  '긍정',
  '적',
  '이든',
  '뭐',
  '든',
  '나',
  '랑',
  '안',
  '맞다',
  '노잼',
  '이라',
  '는걸',
  '새삼',
  '느끼다',
  '해주다',
  '게임'],
 ['명중', '률', '면', '인간', '적', '으로', '맞다', '야하다', '아니다'],
 ['난', '되게', '재밋게햇넹', '딱', '킬링', '타', '임용', '으로', '적당하다'],
 ['쓰레기', '게임', '절때', '사다'],
 ['재미있다', '게임', '이지만', '티어', '올리다', '너무', '오래', '걸리다'],
 ['걍', '이', '겜', '하다', '어리다', '무료', '겜', '인', '하다'],
 ['이', '게임', '의', '단점'],
 ['처음',
  '에는',
  '그냥',
  '그렇다',
  '횡스',
  '크롤',
  '액션',
  '게임',
  '정도',
  '이다',
  '단계',
  '가',
  '넘어가다',
  '개발자',
  '의',
  '재치',
  '가',
  '엿',
  '보이',
  '는',
  '게임',
  '이네',
  '요',
  '중국',
  '도',
  '게임',
  '이',
  '많이',
  '발전',
  '하다',
  '느끼다',
  '있다',
  '게임',
  '이다'],
 ['아', '중독', '성', '있다', '한번', '하다', '멈추다', '힘드다'],
 ['개', '슈레', '기', '게임'],
 ['이', '게임', '은', '정말', '좋다', '게임'],
 ['세',
  '일',
  '을',
  '들다',
  '몇',
  '퍼센트',
  '를',
  '하다',
  '사다',
  '이',
  '한마디',
  '면',
  '되다',
  '하다',
  '사면',
  '그',
  '순간',
  '넌',
  '호갱',
  '이',
  '된거',
  '다',
  '무료',
  '로',
  '뿌리다',
  '받다',
  '카드',
  '만',
  '받다',
  '난',
  '이',
  '게',
  '어떻다',
  '팔리다',
  '되다',
  '그게',
  '차다',
  '궁금하다'],
 ['무료', '겜', '이', '적당하다'],
 ['컴퓨터',
  '로',
  '하다',
  '말다',
  '걍',
  '플스',
  '로',
  '하다',
  '혼자',
  '이상하다',
  '낑기다',
  '말',
  '도',
  '안되다',
  '버벅',
  '거림',
  '시작',
  '한지',
  '시간',
  '만',
  '지우다',
  '버리다',
  '내용',
  '을',
  '보다',
  '조',
  '작',
  '감',
  '이',
  '쓰레기',
  '인',
  '패드',
  '랑',
  '키',
  '보드',
  '다해',
  '보다',
  '혼자',
  '이상하다',
  '낑기다'],
 ['레이싱',
  '을',
  '즐기다',
  '수',
  '있다',
  '다른',
  '오브젝트',
  '와',
  '차량',
  '을',
  '파괴',
  '하다',
  '수',
  '있다',
  '드리프트',
  '가',
  '조금',
  '힘들다',
  '레이싱',
  '이',
  '질린다',
  '트랙',
  '이',
  '너무',
  '쉬다',
  '마이',
  '시티',
  '를',
  '통해',
  '서',
  '자신',
  '의',
  '트랙',
  '을',
  '만들다',
  '수',
  '있다'],
 ['훌륭하다', '절', '대다', '마', '코', '해'],
 ['이', '거', '어뜨', '게', '하다', '굳다', '함'],
 ['계속',
  '적',
  '으로',
  '멈추다',
  '현상',
  '발생',
  '왠만하다',
  '전작',
  '도',
  '재밌다',
  '하다',
  '하다',
  '도저히',
  '불가능하다',
  '포기'],
 ['밸브',
  '가',
  '만들다',
  '게임',
  '인가요',
  '뭔가',
  '하프라이프',
  '같다',
  '느낌',
  '이',
  '드',
  '고',
  '그래픽',
  '이랑',
  '상대',
  '적',
  '이',
  '외계',
  '생명체',
  '이고',
  '협동',
  '게임',
  '이라니',
  '역시',
  '같이',
  '하다',
  '재밌다',
  '추천',
  '하다',
  '무료',
  '겜',
  '이니',
  '더',
  '좋다',
  '네',
  '여',
  '게다가',
  '질',
  '양',
  '하다',
  '싸우다',
  '게임'],
 ['재미있다',
  '좀비',
  '모드',
  '라거',
  '나',
  '하다',
  '모드',
  '도',
  '지원',
  '하지만',
  '알다',
  '사람',
  '없이',
  '혼자',
  '하다',
  '조금',
  '모자라다',
  '느낌'],
 ['심각하다', '노잼', '이다'],
 ['처음',
  '부터',
  '긑',
  '까지',
  '현질',
  '만',
  '유도',
  '하다',
  '게임',
  '어느',
  '시점',
  '이',
  '되다',
  '절대로',
  '이기다',
  '없다',
  '사람',
  '들',
  '하고만',
  '팀',
  '매',
  '치가',
  '되다',
  '걍',
  '하다',
  '하다',
  '게임',
  '게다가',
  '서버',
  '도',
  '엄청',
  '느리다',
  '돈',
  '밖에',
  '모르다',
  '게'],
 ['갓', '겜', '세', '일', '하다', '때', '꼭', '사다'],
 ['베데스다', '오다', '돼지', '새끼', '법', '규'],
 ['마테', '체', '로', '썰다', '다니다', '너무', '재밌다', '없다', '스트레스', '도', '풀리다', '기분'],
 ['실제',
  '카지노',
  '에서',
  '포커',
  '를',
  '하다',
  '한',
  '기분',
  '이',
  '들어서다',
  '너무',
  '좋다',
  '정말',
  '잘',
  '만들다',
  '같다'],
 ['왜', '도트겜', '인데', '프레임', '이', '많이', '끊기다', '게임', '좀', '해보다'],
 ['게임',
  '자체',
  '는',
  '외국',
  '섭',
  '만',
  '보다',
  '때',
  '는',
  '좋다',
  '좆목',
  '잼민',
  '이',
  '들다',
  '여왕벌',
  '이',
  '삼위일체',
  '를',
  '이루다',
  '한국',
  '섭',
  '은',
  '가지',
  '않다',
  '정신건강',
  '에',
  '이',
  '로움',
  '한국',
  '섭',
  '들어가다',
  '절차',
  '가',
  '금융',
  '보안',
  '프로그램',
  '설치',
  '급',
  '이다'],
 ['쓸모없다', '공군'],
 ['솔', '끄다', '무료', '라고', '하다', '퀄', '개쩜'],
 ['서든어택',
  '표절',
  '함',
  '서든어택',
  '도',
  '총',
  '쏘다',
  '움직',
  '이고',
  '한',
  '방',
  '에',
  '죽다',
  '이',
  '겜',
  '이',
  '배낌',
  '에혀',
  '개',
  '노잼',
  '망겜',
  '이',
  '다',
  '이렇다',
  '븅쉬갬'],
 ['허다', '난', '울다'],
 ['퇴근',
  '하고',
  '게임',
  '은',
  '하다',
  '싶다',
  '빡겜할',
  '기운',
  '은',
  '없다',
  '축',
  '늘어지다',
  '쉬엄쉬엄',
  '하다',
  '게임',
  '극',
  '후반',
  '부',
  '까지',
  '진행',
  '하다',
  '엔딩',
  '이',
  '얼마',
  '안남다',
  '참다',
  '못',
  '하고',
  '찍',
  '싸다',
  '드래곤볼',
  '좋아하다',
  '머',
  '하다',
  '동안',
  '나쁘다',
  '않다',
  '남',
  '에게',
  '추천',
  '은',
  '도저히',
  '못',
  '하다'],
 ['레벨',
  '하나',
  '깨다',
  '때',
  '마다',
  '해당',
  '멜로디',
  '를',
  '다시',
  '확인',
  '시키다',
  '게',
  '신경',
  '을',
  '과',
  '하다',
  '자극',
  '하다',
  '그렇다고',
  '딱하다',
  '합주',
  '가',
  '자극',
  '이',
  '적다',
  '건',
  '아니다',
  '것',
  '같다',
  '퍼즐',
  '난이도',
  '는',
  '서서히',
  '높아지다',
  '갑자기',
  '차원',
  '수가',
  '하나',
  '늘다',
  '버리다',
  '전',
  '못',
  '하다'],
 ['게임', '더럽다', '어렵다', '그래픽', '은', '좋다', '노잼'],
 ['탈출',
  '하다',
  '열중',
  '하고',
  '외',
  '에',
  '아무',
  '생각',
  '안',
  '들어서다',
  '좋다',
  '하다',
  '애매하다'],
 ['삭제', '하다', '다시', '생각나다', '하다', '되다'],
 ['한', '패가', '없다', '싯팔'],
 ['점점',
  '내',
  '가',
  '가해자',
  '이고',
  '악마',
  '가',
  '피해자',
  '같다',
  '걍',
  '떄리다',
  '불다',
  '이다',
  '힣'],
 ['카악', '퉤'],
 ['싱글',
  '미션',
  '이',
  '더',
  '많다',
  '하다',
  '아쉬움',
  '이',
  '남다',
  '홈월드',
  '를',
  '플레이',
  '한',
  '기억',
  '이',
  '없다',
  '이',
  '시리즈',
  '를',
  '구매',
  '하다',
  '이유',
  '가',
  '있다',
  '올드팬',
  '이',
  '아니다',
  '구매',
  '를',
  '하다',
  '않다',
  '게',
  '더',
  '나다',
  '있다',
  '이',
  '게임',
  '을',
  '대체',
  '하다',
  '한',
  '게임',
  '들',
  '이',
  '많다'],
 ['머리', '쓰다', '게임', '퍼즐게임', '좋아하다', '유저', '라면', '피다'],
 ['쿠키',
  '클리커',
  '의',
  '스팀',
  '판',
  '굳이',
  '켜다',
  '않다',
  '돈',
  '이',
  '차곡차곡',
  '쌓이다',
  '웹게임',
  '처럼',
  '어쩌다',
  '한번',
  '씩',
  '만',
  '들어오다',
  '업그레이드',
  '해주다',
  '뒤',
  '나가다',
  '충분하다',
  '즐기다',
  '있다',
  '이다'],
 ['들이다',
  '하다',
  '거',
  '보고',
  '받다',
  '너무',
  '스토리',
  '가',
  '짧다',
  '너무',
  '쉬다',
  '더',
  '어렵다',
  '만들다',
  '주거',
  '나',
  '스토리',
  '를',
  '늘리다',
  '게임',
  '산',
  '게',
  '아깝다',
  '지다'],
 ['열차', '루트', '같이', '묶다', '팔다', '좋다', '같다', '초보자', '들', '은', '진짜', '헤매다'],
 ['뿡', '밑', '탙'],
 ['구입',
  '하고',
  '몇',
  '년',
  '째',
  '하다',
  '모르다',
  '안',
  '하다',
  '울트라',
  '와이드',
  '모니터',
  '구입',
  '후',
  '에',
  '테스트',
  '삼다',
  '해보다',
  '눈',
  '깔다',
  '돌아가다',
  '레이싱',
  '은',
  '역시',
  '울트라',
  '와이드',
  '모니터',
  '로',
  '하다',
  '근데',
  '난',
  '역시',
  '나',
  '실력',
  '이',
  '늘',
  '지',
  '않다'],
 ['장',
  '국산',
  '게임',
  '예쁘다',
  '일러스트',
  '단',
  '빠져들다',
  '것',
  '만',
  '같다',
  '동시',
  '에',
  '몰입',
  '이',
  '이상하다',
  '안',
  '되다',
  '스토리',
  '부분',
  '적',
  '인',
  '국어',
  '책',
  '읽다',
  '수준',
  '의',
  '연기',
  '를',
  '하다',
  '다수',
  '의',
  '캐릭터',
  '기본',
  '적',
  '으로',
  '재미',
  '가',
  '없다',
  '혼자',
  '만',
  '커플',
  '없다',
  '영조'],
 ['배경화면', '보다', '게임', '별로', '안', '하다', '되다'],
 ['이',
  '게임',
  '은',
  '개',
  '를',
  '보다',
  '것',
  '뿐',
  '만',
  '아니다',
  '무려',
  '개',
  '를',
  '쓰다듬다',
  '수도',
  '있다',
  '제목',
  '이',
  '게임',
  '을',
  '반도',
  '표현',
  '못',
  '하다',
  '게임',
  '이',
  '죠'],
 ['난이도',
  '가',
  '너무',
  '너무',
  '높다',
  '스테이지',
  '부터',
  '절망',
  '을',
  '맛보다',
  '되다',
  '장르',
  '가',
  '슈팅',
  '인',
  '만큼',
  '은',
  '매우',
  '좋다',
  '창',
  '모드',
  '고정',
  '이',
  '안되다',
  '아쉽다',
  '알트',
  '앤터',
  '로',
  '일일',
  '히',
  '설정',
  '하다',
  '함'],
 ['두',
  '명',
  '이',
  '서',
  '멀티',
  '하다',
  '배아',
  '파',
  '뒤지다',
  '뻔하다',
  '웃음',
  '으로',
  '운동',
  '한다는',
  '얘기',
  '를',
  '실감',
  '함',
  '분동',
  '안',
  '미치다',
  '거마',
  '냥',
  '웃다',
  '배',
  '가',
  '찢어지다',
  '같다',
  '광대뼈',
  '가',
  '쪼개다',
  '같다',
  '그만두다',
  '웃기',
  '싫다',
  '웃기다',
  '끌다',
  '임'],
 ['내', '가', '이', '게임', '뜨다', '하다', '근데', '이', '아니다', '이다', '눈물', '이', '나다'],
 ['언어',
  '압박',
  '이',
  '심하다',
  '게임',
  '이다',
  '생각',
  '보다',
  '어렵다',
  '재미',
  '는',
  '그다지',
  '못',
  '느끼다',
  '게임',
  '이라고',
  '생각',
  '하다'],
 ['훌륭하다',
  '작품',
  '이다',
  '단점',
  '은',
  '스토리',
  '가',
  '너무',
  '짧다',
  '장점',
  '은',
  '역시',
  '툼레이더',
  '이다'],
 ['재미', '는', '있다', '사람', '이', '너무', '없다'],
 ['조', '작', '감', '이', '좋다', '못', '하다'],
 ['어떻다',
  '게임',
  '을',
  '원하다',
  '이',
  '게임',
  '을',
  '구매',
  '하다',
  '정말',
  '자다',
  '알다',
  '같다',
  '이건',
  '어떤',
  '식',
  '으로',
  '들다',
  '그',
  '보다',
  '못',
  '한',
  '게임',
  '일',
  '겁니다',
  '그냥',
  '노잼',
  '세',
  '일',
  '을',
  '하다',
  '구매',
  '하다',
  '않다',
  '것',
  '이',
  '더',
  '좋다',
  '생각',
  '하다'],
 ['재미있다', '와우'],
 ['첫',
  '엔딩',
  '노멀',
  '보다',
  '너무',
  '재밌다',
  '하다',
  '플레이',
  '타임',
  '은',
  '비록',
  '짧다',
  '확',
  '빠지다',
  '드',
  '네',
  '요'],
 ['로켓',
  '을',
  '조종',
  '하다',
  '무사하다',
  '착륙시키다',
  '게임',
  '이렇다',
  '뵈다',
  '어렵다',
  '폭팔',
  '하다',
  '이펙트',
  '가',
  '의외로',
  '멋있다',
  '난',
  '무료',
  '행사',
  '때',
  '얻다'],
 ['세상', '에서', '제일', '아깝다', '불다'],
 ['시간', '이면', '평가', '하다', '돼다', '아니다', '더하다', '요'],
 ['타', '격감', '은', '히오스', '보다', '더', '좋다'],
 ['처음', '엔', '컨텐츠', '가', '없다', '알다', '하다', '하다', '수록', '하다', '많다', '게임'],
 ['아니다',
  '발',
  '내다',
  '좋다',
  '없다',
  '게임',
  '은',
  '하다',
  '수',
  '있다',
  '발매',
  '하다',
  '되다',
  '같다',
  '진짜',
  '가격',
  '도',
  '존나',
  '게',
  '비싸다',
  '기능',
  '은',
  '창작',
  '마당',
  '보다도',
  '못',
  '하고',
  '빙융',
  '시',
  '시',
  '인색',
  '긱들'],
 ['삶다',
  '서로',
  '를',
  '죽',
  '이며',
  '살아가다',
  '자연',
  '과',
  '인간',
  '의',
  '잔혹하다',
  '새롭다',
  '관점',
  '에서',
  '바라보다',
  '게임'],
 ['던파', '충', '들', '은', '이', '게임', '을', '해', '라'],
 ['가성', '비', '최고', '의', '게임', '이다', '친구', '들', '이랑', '즐기다', '좋다'],
 ['임',
  '게임',
  '다운',
  '받다',
  '실행',
  '안되다',
  '다이렉트',
  '문제',
  '로',
  '실행',
  '이',
  '안되다',
  '다이렉트',
  '도',
  '재',
  '설치',
  '하고',
  '최신',
  '버젼',
  '으로',
  '해봤다',
  '소용없다',
  '게임',
  '들어가다',
  '팅기다'],
 ['서버', '에', '사람', '이', '없다', '중국', '인들', '때매', '다', '접다'],
 ['병맛', '으로', '하다', '게임', '가격', '에', '비다', '개꿀'],
 ['멀티플레이', '만큼은', '배필', '급'],
 ['예전',
  '테마',
  '병원',
  '을',
  '생각',
  '하고',
  '구입',
  '하다',
  '오다',
  '잠깐',
  '하다',
  '하다',
  '오후',
  '시',
  '에',
  '시작',
  '을',
  '하다',
  '새벽',
  '을',
  '넘기다',
  '있다',
  '허허',
  '허다',
  '추천',
  '하다',
  '문상',
  '으로',
  '충전',
  '하다',
  '사다'],
 ['사이버',
  '멀미',
  '를',
  '느끼다',
  '싶다',
  '추천',
  '게임',
  '여러가지',
  '해봤다',
  '이',
  '게임',
  '이',
  '처음',
  '이다'],
 ['진짜',
  '꿀잼',
  '게임',
  '이',
  '거',
  '하다',
  '보다',
  '시간',
  '가다',
  '모름',
  '모드',
  '까지',
  '깔다',
  '하다',
  '더',
  '꿀잼'],
 ['찬란하다',
  '빛나다',
  '남자',
  '의',
  '상징',
  '그',
  '길다',
  '짧다',
  '여정',
  '은',
  '개뿔',
  '이',
  '그냥',
  '바바리맨',
  '의',
  '안',
  '잡히다',
  '놀이',
  '겜'],
 ['재밌다',
  '버그',
  '도',
  '없어지다',
  '중세시대',
  '좋아하다',
  '한번',
  '쯤',
  '해보다',
  '함',
  '처음',
  '에',
  '나오다',
  '때',
  '버그',
  '좀',
  '제대로',
  '고치다',
  '나오다',
  '좋다'],
 ['지금', '해도', '꿀잼', '인데', '지금', '해도', '멀미', '남', '으아', '못', '하다', '썽'],
 ['쩌',
  '는',
  '게임',
  '이다',
  '꼭',
  '해보다',
  '더',
  '이상',
  '의',
  '자세하다',
  '설명',
  '은',
  '생략',
  '하다',
  '왜',
  '냐',
  '고요',
  '스포일러',
  '거들다'],
 ['부모님',
  '을',
  '보이다',
  '드리다',
  '아주',
  '좋아하다',
  '근데',
  '어머니',
  '는',
  '고래',
  '가',
  '무섭다',
  '중간',
  '에',
  '포기',
  '하',
  '심',
  '크다',
  '크다',
  '물고기',
  '는',
  '건드리다',
  '도망가다',
  '말미잘',
  '은',
  '건드리다',
  '숨다',
  '버리다',
  '접대',
  '용',
  '으로',
  '좋다',
  '환불',
  '않다',
  '계속',
  '가지',
  '고',
  '있다',
  '생각',
  '이네',
  '요'],
 ['전작',
  '이',
  '개띵작이었',
  '지만',
  '이',
  '게임',
  '은',
  '그냥',
  '망하다',
  '물론',
  '후속작',
  '도',
  '망하다',
  '사다',
  '걍',
  '차라리',
  '복돌',
  '로',
  '해',
  '라'],
 ['내',
  '가',
  '원하다',
  '노래',
  '로',
  '리듬게임',
  '을',
  '하다',
  '이',
  '걸',
  '로',
  '도',
  '대',
  '만족'],
 ['꺼지다', '고', '인물', '쉑들'],
 ['저', '는', '반값', '에', '구매', '하다'],
 ['프레임',
  '은',
  '고정',
  '으로',
  '계속',
  '나오다',
  '게임',
  '자체',
  '문제',
  '로',
  '계속',
  '조금씩',
  '버벅',
  '이고',
  '끊기다',
  '그래픽',
  '도',
  '구림'],
 ['아니다',
  '왜',
  '키안',
  '주다',
  '난리',
  '시발',
  '게임',
  '어떻',
  '게',
  '하',
  '라고',
  '먼저',
  '구매',
  '한',
  '사람',
  '호갱',
  '댓',
  '구연'],
 ['장기', '에프', '가슴', '털'],
 ['실행', '안되다', '늘다', '좃망겜'],
 ['친구',
  '들',
  '이랑',
  '같이',
  '하다',
  '재미있다',
  '멀미',
  '가',
  '너무',
  '심하다',
  '오래',
  '못',
  '하다'],
 ['얼엑', '으로', '내놓다', '개발', '중단', '먹튀'],
 ['너무',
  '허무하다',
  '그리고',
  '주인공',
  '그',
  '특유',
  '의',
  '인생',
  '혼자',
  '다',
  '산',
  '허세',
  '말투',
  '짜증나다'],
 ['네',
  '코파',
  '라',
  '엑스트라',
  '게임',
  '시간',
  '분량',
  '을',
  '분',
  '으로',
  '축약',
  '한',
  '애니매이션',
  '이다',
  '비교',
  '적',
  '짧다',
  '시간',
  '이라',
  '느긋하다',
  '보다',
  '수',
  '있다',
  '앤딩곡',
  '이',
  '좋다',
  '메이플',
  '도',
  '좋다'],
 ['나가다',
  '디',
  '지세',
  '요',
  '유저',
  '좆',
  '목질',
  '꼬',
  '라지',
  '뉴비',
  '배척',
  '오지',
  '는',
  '겜'],
 ['내', '인생', '최고', '의', '생일', '선물'],
 ['엣지', '보다', '훨', '좋다'],
 ['업데이트',
  '전',
  '에는',
  '오버',
  '쿡',
  '보다',
  '쉬다',
  '가면',
  '갈수록',
  '난이도',
  '에',
  '변동',
  '이',
  '없다',
  '많이',
  '실망',
  '을',
  '하다',
  '난이도',
  '가',
  '좀더',
  '높다',
  '나오다',
  '좋다',
  '생각',
  '을',
  '하다',
  '점수',
  '대가',
  '하나',
  '추가',
  '되다',
  '그래도',
  '만족도',
  '가',
  '올라가다',
  '근데',
  '너무',
  '점수',
  '대가',
  '에바',
  '잖다'],
 ['화면', '전환'],
 ['전',
  '쏘다',
  '쏘다',
  '하다',
  '시간',
  '정도',
  '즐겁다',
  '하다',
  '이정',
  '도',
  '가격',
  '만족하다',
  '다만',
  '나중',
  '이',
  '되다',
  '변수',
  '는',
  '거의',
  '없어지다',
  '습격',
  '해오다',
  '부족',
  '들',
  '만',
  '강제',
  '로',
  '강하다',
  '하다',
  '느낌',
  '이',
  '너무',
  '강하다',
  '그',
  '때',
  '부터',
  '재미',
  '가',
  '확',
  '떨어지다',
  '뭔가',
  '다른',
  '방법',
  '도',
  '추가',
  '하다',
  '하다',
  '것',
  '같다'],
 ['웰',
  '메이드',
  '플랫포머',
  '게임',
  '조작',
  '감',
  '브금',
  '액션',
  '맵',
  '구성',
  '스토리',
  '개인',
  '적',
  '으로',
  '전부',
  '다',
  '맘',
  '에',
  '들다',
  '옛날',
  '게임',
  '닌자',
  '가',
  '이',
  '덴',
  '과',
  '매우',
  '비슷하다',
  '상위호환',
  '이라고',
  '볼',
  '수',
  '있다',
  '어리다',
  '적',
  '페미',
  '컴',
  '게임',
  '의',
  '향수',
  '를',
  '느끼다',
  '싶다',
  '사람',
  '들',
  '은',
  '필',
  '구해',
  '야하다',
  '게임'],
 ['재밌다', '고', '인물', '많다', '접다'],
 ['빠요', '엔', '너무', '많다'],
 ['정말로', '재다', '친구', '하다', '더', '재다'],
 ['울', '삼촌', '이', '빠지다', '겜', '근데', '난', '노잼'],
 ['재밌다', '다른사람', '들', '하다', '멘탈', '나가다', '보다', '더', '꿀잼'],
 ['상당하다', '지루하다', '오픈월드'],
 ['게임',
  '이',
  '재밌다',
  '범인',
  '추론',
  '하다',
  '과정',
  '이',
  '너무',
  '억지',
  '임',
  '증거',
  '없이',
  '그냥',
  '추론',
  '만으로',
  '범인',
  '잡다',
  '너무',
  '위험하다',
  '않다'],
 ['남자', '의', '로망'],
 ['노잼',
  '인데',
  '팀',
  '포의',
  '코믹',
  '스럽다',
  '움',
  '을',
  '따르다',
  '싶다',
  '보다',
  '팀',
  '포의',
  '코믹',
  '함',
  '은',
  '캐릭터',
  '의',
  '익숙하다',
  '크다',
  '바탕',
  '을',
  '이루다',
  '있다',
  '흉측하다',
  '잔인하다',
  '뿐이다',
  '캐릭터',
  '와',
  '연출',
  '로는',
  '절대',
  '안',
  '되다',
  '듯'],
 ['은', '이다', '변하다', '거', '없다', '다', '들다', '도망치다'],
 ['재미없다',
  '처음',
  '에는',
  '오',
  '헬기',
  '드론',
  '탱크',
  '드론',
  '이렇다',
  '조종',
  '하다',
  '나름',
  '괜찼',
  '나',
  '싶다',
  '하다',
  '하다',
  '수록',
  '재미',
  '가',
  '없어지다',
  '헬기',
  '딱',
  '번',
  '등장',
  '함',
  '탱크',
  '가다',
  '반',
  '이고',
  '컴퓨터',
  '아군',
  '전혀',
  '도움',
  '안되다',
  '이',
  '걸',
  '왜',
  '하다',
  '모르다',
  '그냥',
  '묶음',
  '떨이',
  '로',
  '하다',
  '사다',
  '엉',
  '아니다'],
 ['아', '제작자', '가', '버리다', '게임'],
 ['게임', '은', '꿀잼', '이지만', '사람', '이', '너무', '없다', '멀티', '하다', '매우', '힘드다'],
 ['이',
  '사양',
  '에',
  '이',
  '가격',
  '에',
  '이렇다',
  '게임',
  '구',
  '하다',
  '어렵다',
  '이건',
  '꼭',
  '사다'],
 ['모든',
  '도전',
  '과제',
  '완료',
  '성공하다',
  '킥스타터',
  '중',
  '하나',
  '인',
  '웨이스트랜드',
  '클래식',
  '한',
  '서양',
  '알피',
  '지',
  '장르',
  '를',
  '좋아하다',
  '꼭',
  '해보다',
  '하다',
  '물론',
  '아쉽다',
  '점도',
  '있다'],
 ['음',
  '걍',
  '공짜',
  '라는',
  '것',
  '도',
  '갓',
  '겜',
  '인데',
  '재미',
  '도',
  '있슴',
  '하지만',
  '쫄보',
  '는',
  '하다',
  '셈',
  '존시나',
  '무서움'],
 ['이',
  '게임',
  '이',
  '다른',
  '게임',
  '과',
  '차별',
  '화',
  '를',
  '두다',
  '있다',
  '그건',
  '이',
  '게임',
  '에는',
  '점프',
  '가',
  '없다',
  '것',
  '이다',
  '생존',
  '겜',
  '인데'],
 ['엉',
  '성하다',
  '컷씬',
  '지루하다',
  '전투',
  '사이드',
  '퀘스트',
  '부족',
  '다른',
  '지역',
  '을',
  '퀘스트',
  '에',
  '따라서',
  '갈수',
  '있다',
  '퀘스트',
  '를',
  '다',
  '깨다',
  '후',
  '에는',
  '가지',
  '못',
  '하다',
  '지역',
  '존재',
  '컷씬',
  '장면',
  '에서',
  '주인공',
  '의',
  '이유',
  '없다',
  '얼굴',
  '검다',
  '칠',
  '등',
  '차',
  '플레이',
  '하다',
  '싶다',
  '않다',
  '게임',
  '이다'],
 ['어렵다', '재밌다'],
 ['서든'],
 ['게임',
  '좆',
  '같이',
  '만',
  '드',
  '네',
  '시발',
  '멀티',
  '좀',
  '해보다',
  '하다',
  '때',
  '마다',
  '팅기다',
  '개',
  '같다',
  '게임',
  '이'],
 ['이', '게', '끝'],
 ['맨', '탈', '박살', '남'],
 ['개다', '씹다', '노잼', '트레일러', '에', '낚임'],
 ['진짜',
  '액션',
  '성',
  '플',
  '래',
  '이타입',
  '바뀌다',
  '참고',
  '해보다',
  '해도',
  '번역',
  '떄매',
  '진짜',
  '하다',
  '싫어지다'],
 ['내',
  '가',
  '이',
  '게임',
  '을',
  '왜',
  '사다',
  '지금',
  '까지',
  '산',
  '게임',
  '중',
  '에',
  '가장',
  '최악',
  '이다'],
 ['하다',
  '키',
  '보드',
  '로',
  '두',
  '명',
  '이',
  '서',
  '하다',
  '있다',
  '사다',
  '사다',
  '뭐',
  '원',
  '이라서',
  '사다'],
 ['출시',
  '되다',
  '지다',
  '년',
  '이',
  '지나다',
  '지금',
  '도',
  '나',
  '에게',
  '있다',
  '이',
  '게임',
  '을',
  '넘어서다',
  '멀티플레이어',
  '늘다',
  '없다'],
 ['게임', '은', '정말', '재미있다', '좋다', '한글', '번역', '을', '하다', '제대로', '해주다'],
 ['이',
  '게임',
  '을',
  '하다',
  '구매',
  '를',
  '결심',
  '하다',
  '돼다',
  '고맙다',
  '네',
  '코파',
  '라',
  '이브'],
 ['트럼프', '님', '이나', '수술', '해드리다'],
 ['스텐리', '재밌다', '하다', '재밌다', '하다', '함'],
 ['재밌다', '팬심', '으로', '한', '듯'],
 ['오다', '내', '가', '해보다', '퍼즐', '게임', '중', '제일', '어렵다'],
 ['를', '지', '원안', '하고', '랑', '만', '지', '원함', '화질', '극혐', '화면', '짤림'],
 ['이', '거', '로그인', '이', '안되다', '이름', '짓다', '힘드다'],
 ['오크',
  '관리',
  '하다',
  '시스템',
  '이',
  '너무',
  '지나치다',
  '정도',
  '로',
  '분량',
  '이',
  '많다',
  '개',
  '지역',
  '이상',
  '점령',
  '하다',
  '직접',
  '하다',
  '오크',
  '성애자',
  '임'],
 ['게임',
  '을',
  '실행',
  '함',
  '과',
  '동시',
  '에',
  '렉',
  '이',
  '걸리다',
  '그런데',
  '웃기다',
  '것',
  '은',
  '정작',
  '보다',
  '켐페인',
  '에',
  '들어가다',
  '렉',
  '이',
  '걸리다',
  '않다',
  '메인',
  '화면',
  '에서',
  '렉',
  '이',
  '걸리다',
  '않다',
  '해주다',
  '게임',
  '을',
  '사고',
  '나서다',
  '정낙',
  '게임',
  '을',
  '못',
  '하고',
  '있다'],
 ['아니다', '이', '게', '안되다', '아니다', '이', '게', '되다'],
 ['내',
  '가',
  '헤봤을때',
  '는',
  '현질',
  '유저',
  '들',
  '이',
  '뉴비',
  '를',
  '학살',
  '하다',
  '장면',
  '을',
  '보다',
  '존나',
  '미치다'],
 ['무섭다', '재미', '가', '없다', '마지막', '엔', '짜증', '만', '가득'],
 ['음',
  '돈',
  '벌리다',
  '만들다',
  '게임',
  '이',
  '아니다',
  '정말',
  '자다',
  '만들다',
  '하다',
  '뭔가',
  '아니다',
  '싶다',
  '그냥',
  '자기',
  '맘',
  '에',
  '들다',
  '만들다',
  '되다',
  '뭐',
  '까지',
  '찍다',
  '동안',
  '재밋',
  '게',
  '자다',
  '하다',
  '나중',
  '에',
  '컨텐츠',
  '더',
  '추가',
  '되다',
  '그때',
  '다시',
  '보다'],
 ['너무', '어렵다', '빼다', '다', '너무', '좋다', '게임', '만들다', '고생', '하', '셧읍니', '다'],
 ['구림'],
 ['서버',
  '관리',
  '가',
  '너무',
  '안되다',
  '피',
  '씨방',
  '에서',
  '접속',
  '하다',
  '렉',
  '은',
  '기본',
  '이고',
  '튕',
  '기기',
  '까지',
  '하니',
  '너무',
  '힘드다'],

In [77]:
cleaned_tokens = []

for tokens in token_list:
    temp = []
    for word in tokens:
        if word not in ko_stopwords:
            temp.append(word)
    cleaned_tokens.append(temp)

data['tokens'] = cleaned_tokens
data.head()

,label,document,tokens
0,0,노래가 너무 적음,"[노래, 너무, 적다]"
1,0,돌겠네 진짜 황숙아 어크 공장 그만 돌려라 죽는다,"[돌다, 진짜, 황숙, 어크, 공장, 그만, 돌리다, 죽다]"
2,1,막노동 체험판 막노동 하는사람인데 장비를 내가 사야돼 뭐지,"[막노동, 체험판, 막노동, 사람, 인데, 장비, 내, 사다, 돼다, 뭐, 지]"
3,1,차악차악 정말 이래서 왕국을 되찾을 수 있는거야,"[차악차악, 정말, 이래서, 왕국, 되찾다]"
4,1,시간 때우기에 좋음 도전과제는 시간이면 다 깰 수 있어요,"[때우다, 좋다, 도전, 과제, 는, 이면, 다, 깨다]"

In [79]:
filtered_list = []

for tokens in data['tokens']:
    temp = []
    for word in tokens:
        if word not in ko_stopwords and len(word) > 1:
            temp.append(word)
    filtered_list.append(temp)

data['tokens'] = filtered_list
data.head(20)

,label,document,tokens
0,0,노래가 너무 적음,"[노래, 너무, 적다]"
1,0,돌겠네 진짜 황숙아 어크 공장 그만 돌려라 죽는다,"[돌다, 진짜, 황숙, 어크, 공장, 그만, 돌리다, 죽다]"
2,1,막노동 체험판 막노동 하는사람인데 장비를 내가 사야돼 뭐지,"[막노동, 체험판, 막노동, 사람, 인데, 장비, 사다, 돼다]"
3,1,차악차악 정말 이래서 왕국을 되찾을 수 있는거야,"[차악차악, 정말, 이래서, 왕국, 되찾다]"
4,1,시간 때우기에 좋음 도전과제는 시간이면 다 깰 수 있어요,"[때우다, 좋다, 도전, 과제, 이면, 깨다]"
5,1,역시 재미있네요 전작에서 할수 없었던 자유로운 덱 빌딩도 좋네요,"[역시, 재미있다, 전작, 자유롭다, 빌딩, 좋다]"
6,1,재미있었습니다,[재미있다]
7,1,은근 쉽지만 은근 어려운 게임,"[은근, 쉬다, 은근, 어렵다, 게임]"
8,0,베 스다 이 개 끼들아 시작할 때 체스판 돌아가는거 분동안 번 봤더나 빡치네 진짜 ...,"[시작, 체스판, 돌아가다, 분동, 보다, 빡치다, 진짜, 무한, 로딩, 버그, 치..."
9,1,시간 분동안 스트레스 다 풀림,"[분동, 스트레스, 풀림]"
10,0,걍 겜임 계정을 못만들어 미친겜,"[겜임, 계정, 만들다]"
11,0,관람객 호랑이 불가,"[관람객, 호랑이, 불가]"
12,1,재미쩡 초반에 좀 힘들어여 도트라서 조아,"[재미, 초반, 힘들다, 도트, 라서, 조아]"
13,1,포켓볼 도 몰랐는데 이걸로 배워 갑니다 심심할때 하면 좋아요 컴퓨터 상대하는거 제대...,"[포켓볼, 모르다, 배우다, 가다, 심심하다, 좋다, 컴퓨터, 상대, 제대로, 이기..."
14,1,트레이아크 사랑해요 핰핰,"[트레이아크, 사랑, 핰핰]"
15,0,좆망겜 하지마 무슨 처음에 키자마자 매칭이 왜 렙하고 매칭되냐,"[좆망, 처음, 매칭, 매칭]"
16,1,뭐랄까 다크소울하는느낌이에요 죽으면 돈 다날라가는 방식 렙업하면서 무한 반복인거같은...,"[뭐라다, 다크, 소울, 느낌, 이에요, 죽다, 다날, 라가, 방식, 렙업, 무한,..."
17,1,원하는거 보실려면 홈페이지 가셔서 패치를 사셔야 합니다 패치가 만원이라 사실상 만원...,"[원하다, 보다, 홈페이지, 갈다, 패치, 사다, 패치, 만원, 이라, 사실, 만원..."
18,0,안해 썩을 까진 그냥 대충 슥슥해도 되더니 에서 판때기를 직접 사용하는데 판을 밟는...,"[안해, 썩을, 까진, 그냥, 대충, 판때, 기르다, 직접, 사용, 밟다, 순간, ..."
19,0,우웩,[우웩]