# BoW 기반 텍스트 분석 연습

1. 적절한 데이터셋을 찾거나 생성하고, 적절한 전처리를 진행한다. [01_preprocessing.ipynb]
2. TF-IDF Vectorizer를 이용하여 벡터화한다.
3. Cosine Similarity를 계산하여 입력된 문자열의 긍/부정을 판단한다.

In [16]:
import pandas as pd

In [17]:
text_df = pd.read_csv('./preprocessing_data.csv', encoding='utf-8')
text_df

,label,document,tokens
0,0,노래가 너무 적음,"['노래', '너무', '적다']"
1,0,돌겠네 진짜 황숙아 어크 공장 그만 돌려라 죽는다,"['돌다', '진짜', '황숙', '어크', '공장', '그만', '돌리다', '죽다']"
2,1,막노동 체험판 막노동 하는사람인데 장비를 내가 사야돼 뭐지,"['막노동', '체험판', '막노동', '사람', '인데', '장비', '사다', ..."
3,1,차악차악 정말 이래서 왕국을 되찾을 수 있는거야,"['차악차악', '정말', '이래서', '왕국', '되찾다']"
4,1,시간 때우기에 좋음 도전과제는 시간이면 다 깰 수 있어요,"['때우다', '좋다', '도전', '과제', '이면', '깨다']"
...,...,...,...
99995,0,한글화해주면 개산다,"['한글화', '해주다', '산다']"
99996,0,개쌉노잼,"['싸다', '노잼']"
99997,0,노잼이네요 분하고 지웠어요,"['노잼', '이네', '분하다', '지우다']"
99998,1,야생을 사랑하는 사람들을 위한 짧지만 여운이 남는 이야기 영어는 그리 어렵지 않습니다,"['야생', '사랑', '사람', '짧다', '여운', '남다', '이야기', '영..."
99999,1,한국의 메탈레이지를 떠오르게한다 진짜 손맛으로 하는게임,"['한국', '메탈레이지', '떠오르다', '진짜', '손맛', '게임']"

In [ ]:
import ast

text_df['tokens'] = text_df['tokens'].apply(ast.literal_eval)
text_df['string'] = text_df['tokens'].apply(lambda x: ' '.join(x))

text_df

,label,document,tokens,string
0,0,노래가 너무 적음,"[노래, 너무, 적다]",노래 너무 적다
1,0,돌겠네 진짜 황숙아 어크 공장 그만 돌려라 죽는다,"[돌다, 진짜, 황숙, 어크, 공장, 그만, 돌리다, 죽다]",돌다 진짜 황숙 어크 공장 그만 돌리다 죽다
2,1,막노동 체험판 막노동 하는사람인데 장비를 내가 사야돼 뭐지,"[막노동, 체험판, 막노동, 사람, 인데, 장비, 사다, 돼다]",막노동 체험판 막노동 사람 인데 장비 사다 돼다
3,1,차악차악 정말 이래서 왕국을 되찾을 수 있는거야,"[차악차악, 정말, 이래서, 왕국, 되찾다]",차악차악 정말 이래서 왕국 되찾다
4,1,시간 때우기에 좋음 도전과제는 시간이면 다 깰 수 있어요,"[때우다, 좋다, 도전, 과제, 이면, 깨다]",때우다 좋다 도전 과제 이면 깨다
...,...,...,...,...
99995,0,한글화해주면 개산다,"[한글화, 해주다, 산다]",한글화 해주다 산다
99996,0,개쌉노잼,"[싸다, 노잼]",싸다 노잼
99997,0,노잼이네요 분하고 지웠어요,"[노잼, 이네, 분하다, 지우다]",노잼 이네 분하다 지우다
99998,1,야생을 사랑하는 사람들을 위한 짧지만 여운이 남는 이야기 영어는 그리 어렵지 않습니다,"[야생, 사랑, 사람, 짧다, 여운, 남다, 이야기, 영어, 그리다, 어렵다]",야생 사랑 사람 짧다 여운 남다 이야기 영어 그리다 어렵다
99999,1,한국의 메탈레이지를 떠오르게한다 진짜 손맛으로 하는게임,"[한국, 메탈레이지, 떠오르다, 진짜, 손맛, 게임]",한국 메탈레이지 떠오르다 진짜 손맛 게임

In [20]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf_vectorizer = TfidfVectorizer()
text_vecs = tfidf_vectorizer.fit_transform(text_df['string'])

text_vecs

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 839969 stored elements and shape (100000, 32360)>